FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN apt-get update \
 && apt-get install -y libicu-dev 

COPY . .

EXPOSE 3000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]